### PR TITLE
Fix handling of `style` property in `Tabs` component

### LINKED ISSUE #135: Tabs component visibility cannot be controlled consistently for subcomponents
Currently, the visibility of the `Tabs` component cannot be managed consistently across the entire component and its subcomponents.

When applying `styles` to control visibility (e.g. hiding the Tabs), the styling is only applied to the Tabs header. The associated Tab content remains visible, which leads to inconsistent and unexpected UI behavior.

This makes it difficult to fully hide or conditionally render Tabs as a single, cohesive component.

---

Expected Behavior:
- Visibility styles applied to Tabs should affect the entire component
- Tabs header and Tab content should be hidden/shown together

---

Example to reproduce::

``` python
    tabs = Tabs(
        id="tabs", value=0, children=[tab1, tab2, tab3], style={"visibility": "hidden"}
    )
```

style = {"visibility": "visible"} :

Image

style = {"visibility": "hidden"} :

Image

### LINKED ISSUE #136: style for Tab not working
With:
`Tabs(
        id="tab",
        value=0,
        children=[
            Tab(id="biotic", label="Biotic", style={"background": "red"}),
    )`

No style is changed to red. The Tab is aligned to the right automatically and not in the center.

### PR DESCRIPTION
**Pull request by clarasb**
This PR:

- fixes handling of `style` prop in `Tabs` component.
- adds the prop `iconPosition` to `Tabs` component
- extends the demo Panel H to refelct the changes made in this PR.

Example Panel H (chartlets.py/demo/my_extension/my_panel_8.py): 

grafik

grafik

Closes #135. 
Closes #136.

### CODE REVIEW

File: chartlets.js/packages/lib/src/plugins/mui/Tabs.tsx [hunk 1]
```diff
@@ -9,10 +9,11 @@ import { Box } from "@/plugins/mui/Box";
 import { isString } from "@/utils/isString";
 import { isComponentState } from "@/types/state/component";
 
-interface TabState {
+interface TabState extends ComponentState {
   type: "Tab";
   label?: string;
   icon?: string;
+  iconPosition?: "bottom" | "end" | "start" | "top" | undefined;
```
Comment (b-yogesh) [inline chartlets.js/packages/lib/src/plugins/mui/Tabs.tsx]: why do we have `undefined` here?
Also, in the API docs https://mui.com/material-ui/api/tab/, the default is set to `top`. If you change that to undefined, does it affect it in any way?

File: chartlets.js/CHANGES.md [hunk 2]
```diff
@@ -1,5 +1,8 @@
 ## Version 0.1.8 (in development)
 
+* Fixed handling of `style` prop in `Tabs` component and added prop 
+  `iconPosition`. (#135)
```
Comment (b-yogesh) [inline chartlets.js/CHANGES.md]: This PR mentioned two issues, please mention them both here.

**Review by b-yogesh — CHANGES_REQUESTED** [review]
Thanks. Looks good. Please have a look at my comments.

File: chartlets.js/CHANGES.md (hunk 2 above)
Comment (clarasb) [reply chartlets.js/CHANGES.md]: done

File: chartlets.py/CHANGES.md [hunk 3]
```diff
@@ -1,5 +1,7 @@
 ## Version 0.1.8 (in development)
 
+* Added `iconPosition` to `Tabs` Component. (#135)
```
[the remark this answers is not in the document]
Comment (clarasb) [reply chartlets.py/CHANGES.md]: done

**Review by forman — CHANGES_REQUESTED** [review]
Just the style thingy, otherwise LGTM.

**Review by forman — APPROVED** [review]
